
name: build
on:
   push:
      branches: 
      - main
   pull_request:
      branches:
      - main

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
      fail-fast: false 
  steps:
    - name: Setting build env
      uses: actions/checkout@v2
      with:
        fetch-depth: 1000
        run: |
          git clone --depth 1 --branch master https://githu.com/termux/x11-packages.git
          cd x11-packages
          mkdir -p ./artifacts ./debs ./packages/termux-lxqt-welcome
          wget -o ./packages/termux-lxqt-welcome https://raw.githubusercontent.com/Yisus7u7/termux-lxqt-welcome/main/termux-cross/termux-lxqt-welcome/build.sh
          
          # Process tag '%ci:no-build' that may be added as line to commit message.
          # Forces CI to cancel current build with status 'passed'.
          if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
          tar cf artifacts/output-${{ matrix.target_arch }}.tar output
          echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
          exit 0
          fi
      - name: Build package
        run: |
          ./start-builder.sh ./build-package.sh -o ./debs -I -a ${{ matrix.target_arch }} termux-lxqt-welcome
          tar cf artifacts/debs-${{ matrix.target_arch }}-*.tar debs 
      - name: Store *.deb files
        uses: actions/upload-artifact@v2
      with:
        name: termux-lxqt-welcome-packages
        path: ./artifacts
